server:
  port: 8080

spring:
  config:
    import:
      - "aws-secretsmanager:prd/cafe"
      - "aws-secretsmanager:rds!cluster-cb0cfbce-010d-4b94-98dc-9bfc73234f43"
      -
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${username}
    password: ${password}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: store-service-s3-bucket
    kms:
      key-arn: arn:aws:kms:ap-northeast-2:322533971309:key/7d04c5d4-322c-48a0-ad51-9f73934b503d
    region:
      static: ap-northeast-2
    directory:
      menu: menu

gateway:
  secret: ${GATEWAY_SECRET}