server:
  port: 8082

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    kms:
      key-arn: ${S3_KEY_ARN}
    region:
      static: ${S3_REGION}
    directory:
      menu: ${S3_DIRECTORY}

gateway:
  secret: ${GATEWAY_SECRET}

simulation:
  enabled: true
  orders-per-store-min: 15
  orders-per-store-max: 40

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.zaxxer.hikari: DEBUG